site_name: CatMapPy
site_description: Python interface to the CatMapper API
site_url: https://projectcatmapper.github.io/CatMapPy/
repo_url: https://github.com/ProjectCatMapper/CatMapPy
repo_name: ProjectCatMapper/CatMapPy

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Usage: usage.md
  - API Reference: api-reference.md
  - Contributing: contributing.md
  - Citation: citation.md
  - License: license.md

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ProjectCatMapper
      name: ProjectCatMapper organization

copyright: Copyright 2026 ProjectCatMapper
